name: 'DDR Security CAPTCHA'
type: 'Droptica’s Drupal Recipes'
description: 'Installs and configures the CAPTCHA module for enhanced form security.'

install:
  - captcha
  - image_captcha

config:
  actions:
    captcha.settings:
      simpleConfigUpdate:
        enable_globally: 1
        enable_globally_on_admin_routes: false
        default_challenge: image_captcha/Image
        description: 'This question is for testing whether or not you are a human visitor and to prevent automated spam submissions.'
        title: CAPTCHA
        administration_mode: false
        administration_mode_on_admin_routes: false
        whitelist_ips: ''
        wrong_captcha_response_message: 'The answer you entered for the CAPTCHA was not correct.'
        default_validation: 1
        persistence: 1
        enable_stats: false
        log_wrong_responses: false
    
    image_captcha.settings:
      simpleConfigUpdate:
        image_captcha_fonts_preview_map_cache:
          c4e145adf0facb2a37cdc58551af9a93a5232c722a278c14e6b3a89cf0224586:
            uri: modules/contrib/captcha/modules/image_captcha/fonts/Tuffy/Tuffy_Bold.ttf
            filename: Tuffy_Bold.ttf
            name: Tuffy_Bold
          3dbed886c81a681a313bc6297f53db5699401194490d38621f05c7bdf06cf1f5:
            uri: modules/contrib/captcha/modules/image_captcha/fonts/Tuffy/Tuffy.ttf
            filename: Tuffy.ttf
            name: Tuffy
          986462a9e165423b12587d83a363091b837f54db5d7337cb3da3f97f54104fbb:
            uri: modules/contrib/captcha/modules/image_captcha/fonts/Tesox/tesox.ttf
            filename: tesox.ttf
            name: tesox
        image_captcha_fonts:
          - 986462a9e165423b12587d83a363091b837f54db5d7337cb3da3f97f54104fbb
          - 3dbed886c81a681a313bc6297f53db5699401194490d38621f05c7bdf06cf1f5
        image_captcha_font_size: 30
        image_captcha_character_spacing: '1.2'
        image_captcha_image_allowed_chars: aAbBCdEeFfGHhijKLMmNPQRrSTtWXYZ23456789
        image_captcha_code_length: 5
        image_captcha_rtl_support: 0
        image_captcha_background_color: '#ffffff'
        image_captcha_foreground_color: '#000000'
        image_captcha_foreground_color_randomness: 100
        image_captcha_file_format: 1
        image_captcha_distortion_amplitude: 0
        image_captcha_bilinear_interpolation: 0
        image_captcha_dot_noise: 0
        image_captcha_line_noise: 0
        image_captcha_noise_level: 5
        image_captcha_text_refresh: 'Reload Captcha'
